services:
  eureka:
    build: ./eureka
    image:  eureka:latest
    container_name: eureka-server
    ports:
      - "8076:8076"
    networks:
      - microservices-network

  gateway:
    build: ./gateway
    image:  getway:latest
    container_name: gateway-service
    ports:
      - "8066:8066"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  restaurant-service:
    build: ./microservices/restaurant
    image:  restaurant:latest
    container_name: restaurant-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  commande-service:
    build: ./microservices/commande
    image: commande:latest
    container_name: commande-service
    ports:
      - "8050:8050"
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  annonce-service:
    build: ./microservices/annonce
    image: annonce:latest
    container_name: annonce-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network
  fournisseur-service:
    build: ./microservices/fournisseur
    image: fournisseur:latest
    container_name: fournisseur-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network







networks:
  microservices-network:
    driver: bridge
