spring:
  application:
    name: authService

  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
